### ISSUE TITLE
RMC Signal Multiplexer 3.0.0 Multiplexer Issue

### ISSUE THREAD

**Issue by sabinoj** [chicagoedt/Circuit_Boards#9]
It just hit me today that the multiplexer will not be able to correctly operate with the USB-to-RS-232 IC because it is only designed to take TTL. I will have to modify the design to accomodate a USB-to-TTL IC rather than a USB-to-RS-232 IC and place a TTL-to-RS-232 IC after the multiplexer.

THIS WILL HALT MANUFACTURING OF THIS DESIGN FOR THE TIME BEING UNTIL I CAN GET AROUND TO REVISING THIS.

**Comment by l0g1x** [comment]
is there a different multiplexer we can go with..?

**Comment by sabinoj** [comment]
I'll look into that right now.

**Comment by sabinoj** [comment]
Closed due to the revision being halted.
